### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by sang-codecademy** [Saad888/Tome-Rater#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ No syntax errors. Great job writing all valid Python code without any errors or issues!
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ You implemented the functions successfully. Also, GREAT JOB WITH HANDLING ERRORS. Many people forget to test their code and make sure it can handle wrong errors. But this is a very important part of programing in the real world where there are always edge-cases. Next time, you can also look into something called Jupyter Notebook, which is a popular method with programmers to not only show but also visualize the results of their code side-by-side.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4/4
* _Comment(s):_ Great job defining and naming classes and functions. Everything was written correctly and you simplified you code as much as possible. You also effectively refactored your code so that a single function doesn't try to do everything, such as with your print_users, etc. functions.
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4/4
* _Comment(s):_ Your knowledge of Python and general computing is very apparent in your code. You consistently used Python language features where appropriate.
 
### Overall Score: 16/16
Overall you did a fantastic job on this project! I can tell that you have learned a lot from the PWP course and hope you continue on with your Python journey.

**Comment by Saad888** [comment]
Thanks!
